### ISSUE TITLE
golang dep tool expects to own the path ".go", so we should move away from that.

### ISSUE THREAD

**Issue by rfay** [drud/build-tools#11]
This needs to be confirmed, but I took a quick spin with the new [golang "dep" tool](https://github.com/golang/dep), and it expected to use **.go** (as a file, I think), but we have it as a directory. IMO we should move out of the way soon, maybe .build or something.

**Comment by cyberswat** [comment]
Thanks for submitting this.  Can you help us get this ticket into a state where it meets our [request guidelines](https://github.com/drud/community/blob/master/development/request_guidelines.md)?

**Comment by rfay** [comment]
This is a feature request. build-tools should use ".gobuild' as the directory name for transient files instead of .go, because "go dev" seems to be using a file called .go and we'll eventually collide.
