### ISSUE TITLE
build-tools should document its version when installed

### ISSUE THREAD

**Issue by rfay** [drud/build-tools#13]
It's easy to see from the commit log what build-tools is installed, but it would be much better if it just self-documented its version when installing.

**Comment by cyberswat** [comment]
@rfay Thanks for submitting this.  Can you help us get this ticket into a state where it meets our [request guidelines](https://github.com/drud/community/blob/master/development/request_guidelines.md)?

**Comment by rfay** [comment]
This is a feature request. During a build-tools update create a file build-tools/build-tools-VERSION.txt which contains the version of build-tools which is contained in the build-tools directory.
