### ISSUE TITLE
Deprecate FROM special handling for dockerfiles

### ISSUE THREAD

**Issue by rfay** [drud/build-tools#34]
## What happened (or feature request):

Our preprocessing approach to providing the upstream docker build is no longer necessary, as Docker provides replaceable FROM now.  See https://github.com/moby/moby/pull/31352 and https://www.jeffgeerling.com/blog/2017/use-arg-dockerfile-dynamic-image-specification

We should probably deprecate that approach and move handling into the Dockerfile (or Dockerfile.in). A fair bit of effort went into the Dockerfile processing for this exact feature, so it's slightly painful to work our way back out of it. But I really don't like having the FROM in the Makefile anyway, so maybe we can battle out, especially in the docker.nginx-php-fpm family of containers.

## Related source links or issues (like source JIRA issue):

**Comment by rickmanelius** [comment]
Would need a little more information IMHO before proceeding. What's the pros/cons of sticking with the current approach and what's the rough guess LOE?

**Comment by rfay** [comment]
I suspect we should just document how this can be done downstream (in repos like ddev) using the Docker technique. Then we use the docker technique there, and the preprocessing done by build-tools just becomes superfluous, but nothing is broken.

**Comment by rickmanelius** [comment]
Seems reasonable to address when we're back onto bootstrap.

**Comment by rfay** [comment]
This is not related to bootstrap, it's something that affects all of our updated repos that build containers. It's also not urgent in any way. This issue is just here to steer us back to a better way of handling it.

**Comment by rfay** [comment]
We don't actually do multi-level images any more, so the only thing required here is to start using Dockerfile instead of Dockerfile.in, only preprocess Dockerfile.in if it exists.
